### ISSUE TITLE
repo init not working!

### ISSUE THREAD

**Issue by varsha-2508** [kkamagui/shadow-box-for-arm#3]
I am trying to install the shadow box for raspberry pi 3b+ and I am getting an error while running the 
repo init -u https://github.com/kkamagui/manifest.git -m rpi3.xml -b secure-pi command. 
I get the following error 
Traceback (most recent call last):
  File "/home/nagulan/shadow-box/.repo/repo/main.py", line 628, in <module>
    _Main(sys.argv[1:])
  File "/home/nagulan/shadow-box/.repo/repo/main.py", line 602, in _Main
    result = run()
  File "/home/nagulan/shadow-box/.repo/repo/main.py", line 595, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/nagulan/shadow-box/.repo/repo/main.py", line 264, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/nagulan/shadow-box/.repo/repo/subcmds/init.py", line 525, in Execute
    self._LinkManifest(opt.manifest_name)
  File "/home/nagulan/shadow-box/.repo/repo/subcmds/init.py", line 348, in _LinkManifest
    self.manifest.Link(name)
  File "/home/nagulan/shadow-box/.repo/repo/manifest_xml.py", line 246, in Link
    self.Override(name)
  File "/home/nagulan/shadow-box/.repo/repo/manifest_xml.py", line 239, in Override
    self._Load()
  File "/home/nagulan/shadow-box/.repo/repo/manifest_xml.py", line 579, in _Load
    self._ParseManifest(nodes)
  File "/home/nagulan/shadow-box/.repo/repo/manifest_xml.py", line 687, in _ParseManifest
    project = self._ParseProject(node)
  File "/home/nagulan/shadow-box/.repo/repo/manifest_xml.py", line 972, in _ParseProject
    self._ParseLinkFile(project, n)
  File "/home/nagulan/shadow-box/.repo/repo/manifest_xml.py", line 1126, in _ParseLinkFile
    self._ValidateFilePaths('linkfile', src, dest)
  File "/home/nagulan/shadow-box/.repo/repo/manifest_xml.py", line 1107, in _ValidateFilePaths
    '<%s> invalid "src": %s: %s' % (element, src, msg))
error.ManifestInvalidPathError: <linkfile> invalid "src": ../toolchains/aarch64/bin/aarch64-linux-gnu-gdb: bad component: ..
nagulan@nagulan-ThinkPad-P43s:~/shadow-box$ 

please help!

**Comment by kkamagui** [comment]
Hi @varsha-2508 ,

I just changed the rpi3.xml for avoiding the error when repo init. Please do it again.

Best regards,

Seunghun

**Comment by varsha-2508** [comment]
Thank you so much for replying! I had one more question, when I try to boot the pi with the sd card; the red light flashes four times and I see nothing on the monitor. Could you please suggest what might be wrong? Thanks!

**Comment by kkamagui** [comment]
@varsha-2508 , I guess you used the wrong firmware or OS image. This repository is for RPI 3, not RPI 3B or 3B+. So, that's the reason I think. :)

**Comment by varsha-2508** [comment]
So in order to run it on 3b+, what are the changes that I must be doing?

**Comment by kkamagui** [comment]
Hi @varsha-2508 ,

I'm not sure but you have to change the dtd file and the kernel for your RPI 3B+ because it's the base system for your PI. Or please search the OPTEE version for RPI3 B+.

Best regards,

Seunghun
